name: Build with Infisical Secrets

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Infisical CLI
        run: |
          curl -1sLf "https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh" | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Authenticate with Infisical
        run: infisical login --token ${{ secrets.INFISICAL_TOKEN }}

      - name: Run your command with secrets injected
        run: infisical run --env=development "npm run build"
